#ifndef MIME_PARAMS_H
#define MIME_PARAMS_H
#define DC_THRESHOLD 5279
#define DPC_THRESHOLD 4547
#define SC_THRESHOLD 1899
#define _IP_MARK "."
#define DISTINCT_NUM 2431002

// Ours
#define SAMPLING_RATE 0.1

#endif //MIME_PARAMS_H
